sudo: false

language: scala

scala:
  - 2.12.8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - \$HOME/.ivy2/cache
    - \$HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock

jdk:
  - openjdk11

script:
  - sbt clean coverage test coverageReport coverageAggregate

after_success:
  - sbt coveralls